### ISSUE TITLE
On separate branch, implement periodic pulls of new entries from raft datastore

### ISSUE THREAD

**Issue by gabbifish** [gabbifish/distributed-dns#1]
This could be valuable to leave on a separate branch--it would be awesome to compare this faster (though less safe) implementation to the safe, but slower approach we use now (that is, read from the raft datastore every time someone performs a query!)

**Comment by eorbay** [comment]
After much reading through source code, testing, trying build custom data store from inheriting SyncObj, I realized that simply deleting most of our code and all data structures except rr_raft accomplish this.

I'll simply add a switch for safety.
